[project]
requires-python = ">= 3.11"
name = "lambda-runtimes"
dynamic = ["version"]
dependencies = [
  "boto3",
  "requests",
  "tzdata"
]
[dependency-groups]
dev = [
  "pytest",
  "pre-commit",
  "requests"
]
lint = [
  "ruff"
]
